service: aws-node-http-api-project
plugins:
  - serverless-esbuild
  - serverless-offline
provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 128 # optional, in MB, default is 1024
  timeout: 10 # optional, in seconds, default is 6
  stage: ${opt:stage, 'dev'}
  region: sa-east-1

functions:
  hello:
    handler: src/handler.hello
    events:
      - httpApi:
          path: /
          method: get

package: 
  individually: true
custom:
  esbuild:

    bundle: true
    minify: false
    watch:
      pattern: ['src/**/*.ts']